# Generated by Django 5.1.2 on 2024-11-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_payment_method_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
    ]
