# Generated by Django 5.1.2 on 2024-11-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_payment_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='payment_screenshot',
        ),
    ]
