# Generated by Django 5.1.2 on 2024-11-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_student_payment_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
    ]
