# Generated by Django 5.1.2 on 2024-11-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_instructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='video',
            field=models.FileField(max_length=255, upload_to='course_videos/'),
        ),
    ]
