# Generated by Django 5.1.2 on 2024-11-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_instructor', '0004_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
